Łukasz
nizwant/Warsztaty_Badawcze pull request #15
Opened 2023-05-24 08:50 UTC by LukaszGrabarski

2023-05-24 12:46 UTC, szuvarska requested changes
Bardzo ładnie dobrane wykresy, ale parę uwag.

2023-05-24 12:46 UTC, szuvarska commented on src/Parameters/parametrs_testing.R
Pozmieniaj "parametrs" na "parameters", bo to ani po polsku, ani po angielsku.

2023-05-24 12:46 UTC, szuvarska commented on src/Parameters/parametrs_testing.R
> +  labs(x= 'Mean Worse Rate', y='Parametrs Values', title = "Parameters' impacts on Worse Rate ")+
Szczególnie tutaj, bo się pokazuje na wykresie.

2023-05-24 12:46 UTC, szuvarska commented on src/Parameters/results/parameters_distr.png
Te osie nie powinny być odwrotnie? Na OX masz wartości parametrów, a tam są te same wartości dla wszystkich wykresów, więc coś nie tak.

2023-05-24 12:46 UTC, szuvarska commented on src/Parameters/results/parameters_distr.png
Też nie wiem, czy będzie wiadomo, czym jest Worse Rate. Karolina to nazwała "percent above best solution" i wydaje mi się, że to mówi więcej. Chyba że to jest u Ciebie jeszcze czymś innym.

2023-05-24 12:46 UTC, szuvarska commented on src/Parameters/results/Worse_rate_distr.png
Warto dodać do legendy, jakie problemy zostały zaklasyfikowane jako "big", "medium" i "small".

2023-05-24 12:46 UTC, szuvarska commented on src/Parameters/results/grid_search_6.csv
Można się zastanowić, czy do raportu nie dać też jakichś tabelek z wynikami, aczkolwiek trzebaby to pewnie okroić. Do prezki można pominąć.

2023-06-02 20:17 UTC, LukaszGrabarski commented
Wykresy naprawione, nazwy zmienione. Kod, pliki oczyszczone

2023-06-02 20:54 UTC, LukaszGrabarski commented
ALL CONFLICTS RESOVLED!! HURRAY!

2023-06-02 20:56 UTC, merged